[package]
name = "git-rust"
version = "0.1.1"
edition = "2024"

[dependencies]
dotenvy = "0.15"
clap = { version = "4.5.60", features = ["derive"] }
claude-agent-sdk-rs = "0.6.4"
claude-sdk = "1.0.0"
git2 = "0.20.4"
tokio = { version = "1.49.0", features = ["full"] }
